# Generated by Django 6.0.1 on 2026-02-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='route',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteStop',
        ),
    ]
